# Site
name: Lambert Leong
description: Professional Protfolio
meta_description: Lambert Leong's Professional Portfolio
logo: /assets/images/landing_page/logo.png
favicon: /assets/images/landing_page/favicon.ico
paginate: 6
baseurl:
email: 'lamberttleong@gmail.com'
google_analytics: UA-121492082-1
disqus: lambertleong
sharethis: lamberttleong@gmail.com

# Authors
authors:
  Lambert:
    name: Lambert
    display_name: Lambert Leong
    image: /assets/images/lambert_prof_2020_2.jpg
    email: lamberttleong@gmail.com
    web: lambertleong.com
    twitter:
    description: Hi, I am Lambert Leong.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
#jekyll-archives:
#  enabled:
#    - categories
#  layout: archive
#  permalinks:
#    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: leonglambert
  card: summary

facebook:
  app_id:
  publisher:
  admins:

social:
name: Lambert Leong
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://github.com/
